# Generated by Django 4.1.7 on 2023-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0013_advantage_assignment_choice_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Небольшое описание'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название преимущества'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_review',
            field=models.TextField(max_length=255, verbose_name=''),
        ),
    ]
