# Generated by Django 4.1.7 on 2023-05-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0014_alter_advantage_description_alter_advantage_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Небольшое описание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_review',
            field=models.TextField(max_length=300, verbose_name=''),
        ),
    ]
