# Generated by Django 4.1.7 on 2023-05-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0015_alter_advantage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='text_review',
            field=models.TextField(max_length=300, verbose_name='Текст отзыва'),
        ),
    ]
